language: python

python:
  - "2.7"
  - "3.4"
  - "pypy"

matrix:
  allow_failures:
    python: pypy

before_install: ./.travis/before_install

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test

after_success:
  - coveralls

services: mongodb

branches:
  only:
    - master
    - unstable